version: "3"
services:
  web:
    build: ./front
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: "./front/index.html"
        - action: rebuild
          path: "./front/main.js"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./.mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    restart: always
    environment:
      DB_URI: "${MONGO_URI}"